apiVersion: v1
kind: ConfigMap
metadata:
  name: build-integrations-sample
  namespace: default
data:
  text: |
    Calm down, Marty, I didn’t disintegrate anything. The molecular structure of Einstein and the car are completely intact. Marty you gotta come back with me. Yoo. Yoo.
